### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by ibrarturi** [maksyutin/yii2-dual-list-box#1]
Hi,

I tried to install your extension through composer but I am getting error (see attached file).

Thanks
![error](https://cloud.githubusercontent.com/assets/3693201/6078378/c7f5f030-ae19-11e4-8cce-ce97650f3dd1.jpg)

**Comment by ibrarturi** [comment]
By adding the following line: "maksyutin/yii2-dual-list-box": "dev-master" to the composer.json, I was able to install this extension.

**Comment by maksyutin** [comment]
add
