### ISSUE TITLE
no language setting ? its not in english

### ISSUE THREAD

**Issue by skeeran** [maksyutin/yii2-dual-list-box#3]
Hi,
english Translation would be helpful.. otherwise working perfect

thanks

**Comment by maksyutin** [comment]
Add language options and make default english

maksyutin\duallistbox\Widget::widget([
                'attribute' => 'list_sphera',
                'nametitle' => 'рубрики',
                'model' => $model,
                'data' => $sphera,
                'lngOptions' => [
                    'warning_info' => 'Вы уверены, что хотите выбрать такое количество элементов? Возможно Ваш браузер может перестанет отвечать на запросы..',
                    'search_placeholder' => 'Фильтр',
                    'showing' => ' - показано',
                    'available' => 'Имеющиеся',
                    'selected' => 'Выбранные'
                ]
            ]);
